services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    hostname: backend-host
    ports:
      - "5000:5000"
    networks:
      - compose-networks


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000/submit
    depends_on:
      - backend
    networks:
      - compose-networks


networks:
  compose-networks: {}